{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data.dbcredentials }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
